name: ModDB Addon Upload/Update
description: Uploads or updates an addon on ModDB using the moddb Python library
author: Tosox

inputs:
  mode:
    description: "upload or update"
    required: true
  moddb_username:
    required: true
  moddb_password:
    required: true
  mod_url:
    required: false
  addon_url:
    required: false
  addon_path:
    required: false
  thumbnail_path:
    required: false
  name:
    required: false
  summary:
    required: false
  description:
    required: false
  category:
    required: false
  platforms:
    required: false
  credits:
    required: false
  tags:
    required: false
  license:
    required: false
  file_url:
    required: false

outputs:
  result:
    description: "Whether the addon was uploaded or updated"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python requirements
      shell: bash
      run: pip install -r requirements.txt

    - name: Run moddb script
      shell: bash
      run: python src/moddb_cli.py
      env:
        MODE: ${{ inputs.mode }}
        MODDB_USERNAME: ${{ inputs.moddb_username }}
        MODDB_PASSWORD: ${{ inputs.moddb_password }}
        MOD_URL: ${{ inputs.mod_url }}
        ADDON_URL: ${{ inputs.addon_url }}
        ADDON_PATH: ${{ inputs.addon_path }}
        THUMBNAIL_PATH: ${{ inputs.thumbnail_path }}
        NAME: ${{ inputs.name }}
        SUMMARY: ${{ inputs.summary }}
        DESCRIPTION: ${{ inputs.description }}
        CATEGORY: ${{ inputs.category }}
        PLATFORMS: ${{ inputs.platforms }}
        CREDITS: ${{ inputs.credits }}
        TAGS: ${{ inputs.tags }}
        LICENSE: ${{ inputs.license }}
        FILE_URL: ${{ inputs.file_url }}
