name: 'Upload a ModDB release asset'
description: 'Upload a release asset to ModDB'
author: 'Tosox'
inputs:
  moddb_username:
    description: 'ModDB account username'
    required: true
  moddb_password:
    description: 'ModDB account password'
    required: true
#outputs:
#  num_squared:
#    description: 'Square of the input'
#    # Need to specify the extra `value` field for `composite` actions
#    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      shell: bash
      run: pip install -r requirements.txt
    - name: Pass Inputs to Shell
      shell: bash
      run: |
          echo "MODDB_MOD_URL=${{ inputs.moddb_mod_url }}" >> $GITHUB_ENV
    - name: Upload ModDB release asset
      shell: bash
      id: upload-moddb-release
      run: python src/upload_release.py
