name: 'Test Action'
on: [push]

jobs:
  upload_test_asset:
    runs-on: 'ubuntu-latest'
    name: 'Upload test asset'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 'Upload test asset'
        uses: ./ # Uses an action in the root directory
        # or use a released Github Action
      - env:
          MODDB_USERNAME: ${{ secrets.MODDB_USERNAME }}
          MODDB_PASSWORD: ${{ secrets.MODDB_PASSWORD }}
