name: Test Action

on:
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload ModDB Addon
        id: upload
        uses: ./
        with:
          mode: upload
          moddb_username: ${{ secrets.MODDB_USER }}
          moddb_password: ${{ secrets.MODDB_PASS }}
          mod_url: https://www.moddb.com/mods/my-mod
          addon_path: out/addon.zip
          thumbnail_path: out/preview.jpg
          name: My Addon
          summary: Short summary
          description: Long HTML description
          category: player_skin
          platforms: windows,linux
          tags: patch,release,test
          license: mit

      - name: Log result
        run: echo "Result was ${{ steps.upload.outputs.result }}"
