name: 'Test Action'

on:
  workflow_dispatch:

jobs:
  test_action:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 'Upload test asset'
        uses: ./
        env:
          #MODDB_USERNAME: ${{ secrets.MODDB_USERNAME }}
          MODDB_PASSWORD: ${{ secrets.MODDB_PASSWORD }}
        with:
          moddb_mod_url: 'https://moddb.com/mods/stalker-anomaly/'

